# Generated by Django 5.1.4 on 2024-12-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_alter_ingredient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='id_ingredient',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='id_ingredient'),
            preserve_default=False,
        ),
    ]
