# Generated by Django 5.1.4 on 2024-12-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_ingredient_id_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='id_ingredient',
            field=models.PositiveIntegerField(unique=True, verbose_name='id_ingredient'),
        ),
    ]
