# Generated by Django 5.1.4 on 2024-12-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pseudo', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1)),
            ],
        ),
    ]
